services:
  - type: web
    name: resume-screening
    runtime: python

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: gunicorn resume_screening.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resume_screening.settings

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"